version: '3.0.0.{build}'
image: Visual Studio 2017
platform: x86
configuration: Release
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '3.0.0 Base'
before_build:
 - nuget restore
build_script:
 - msbuild /verbosity:minimal "SafeExamBrowser.sln"
after_build:
 - appveyor PushArtifact "Setup\bin\%CONFIGURATION%\Setup.msi" -FileName "SEB_%APPVEYOR_BUILD_VERSION%_Setup.msi" -DeploymentName "SEB_%APPVEYOR_BUILD_VERSION%_Setup"
 - appveyor PushArtifact "SetupBundle\bin\%CONFIGURATION%\SetupBundle.exe" -FileName "SEB_%APPVEYOR_BUILD_VERSION%_SetupBundle.exe" -DeploymentName "SEB_%APPVEYOR_BUILD_VERSION%_SetupBundle"
artifacts:
 - path: SafeExamBrowser.Runtime\bin\$(platform)\$(configuration)
   name: 'SEB_$(appveyor_build_version)_Application'
   type: zip
 - path: SebWindowsConfig\bin\$(platform)\$(configuration)
   name: 'SEB_$(appveyor_build_version)_Configuration'
   type: zip
 - path: SafeExamBrowser.ResetUtility\bin\$(platform)\$(configuration)
   name: 'SEB_$(appveyor_build_version)_Reset'
   type: zip
 - path: SafeExamBrowser.Service\bin\$(platform)\$(configuration)
   name: 'SEB_$(appveyor_build_version)_Service'
   type: zip
